name: Deployment
on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      action:
        description: "Run Terraform Apply or Destroy?"
        type: string
        required: false

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_PRIME }}
  AWS_REGION: us-east-1

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: My First Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_LOGIN_TOKEN }}
      
      - name: Run Terraform Init
        run: terraform init 
      - name: Run Terraform Deployment
        run: terraform ${{ github.event.inputs.action }} -auto-approve -var "public_key_content=${{ secrets.TF_LOGIN_TOKEN }}"
        if: ${{ github.event.inputs.action == 'apply' || github.event.inputs.action == 'destroy' }}
